# CUSTOM config for local ollama qwen model

agent:
  model:
    name: ollama/qwen2.5-coder:7b-instruct
    # name: ollama/mistral:7b-instruct-v0.3-q4_K_M
    per_instance_cost_limit: 0
    per_instance_call_limit: 15
    temperature: 0.1
    api_key: ollama
    api_base: http://localhost:11434
    max_input_tokens: 32000
    total_cost_limit: 0
