agent:
  model:
    name: ollama/qwen2.5-coder:7b-instruct
    per_instance_cost_limit: 0
    per_instance_call_limit: 15
    temperature: 0.0
    api_key: ollama
    api_base: http://localhost:11434
    max_input_tokens: 32000
    total_cost_limit: 0
    # max_output_tokens:
    # custom_tokenizer:
    # retry:

# class name GenericAPIModelConfig

# agent:
#   type: DefaultAgent

# model:
#   name: openai/qwen2.5-coder:7b-instruct
#   temperature: 0.2
#   max_output_tokens: 2048
#   parse_function: thought_action

# per_instance_cost_limit: 0
# total_cost_limit: 0



# for use later on when making sub-models 
# planner:
#   temperature: 0.3
#   max_tokens: 2048

# coder:
#   temperature: 0.1
#   max_tokens: 4096

# reflection:
#   temperature: 0.2
#   max_tokens: 2048
